SCREEN_WIDTH = 480
SCREEN_HEIGHT = 480
FPS = 30
TILE_SIZE = 24
MAP_TILES_X = 20
MAP_TILES_Y = 20

# Stats: HP, ATK, DEF, SPD, SPATK, SPDEF, total BST
STAT_HP = 0
STAT_ATK = 1
STAT_DEF = 2
STAT_SPD = 3
STAT_SATK = 4
STAT_SDEF = 5

# Types
TYPE_NORMAL = "Normal"
TYPE_FIRE = "Fire"
TYPE_WATER = "Water"
TYPE_GRASS = "Grass"
TYPE_ELECTRIC = "Electric"
TYPE_ICE = "Ice"
TYPE_DARK = "Dark"
TYPE_SPIRIT = "Spirit"
TYPE_DRAGON = "Dragon"
TYPE_EARTH = "Earth"
TYPE_WIND = "Wind"
TYPE_LIGHT = "Light"

ALL_TYPES = [
    TYPE_NORMAL, TYPE_FIRE, TYPE_WATER, TYPE_GRASS, TYPE_ELECTRIC,
    TYPE_ICE, TYPE_DARK, TYPE_SPIRIT, TYPE_DRAGON, TYPE_EARTH,
    TYPE_WIND, TYPE_LIGHT,
]

TYPE_COLORS = {
    TYPE_NORMAL: (168, 168, 120),
    TYPE_FIRE: (240, 128, 48),
    TYPE_WATER: (104, 144, 240),
    TYPE_GRASS: (120, 200, 80),
    TYPE_ELECTRIC: (248, 208, 48),
    TYPE_ICE: (152, 216, 216),
    TYPE_DARK: (112, 88, 72),
    TYPE_SPIRIT: (160, 96, 192),
    TYPE_DRAGON: (112, 56, 248),
    TYPE_EARTH: (224, 192, 104),
    TYPE_WIND: (168, 216, 240),
    TYPE_LIGHT: (248, 248, 144),
}

# Effectiveness:攻撃タイプ -> 被弾タイプ -> 倍率
TYPE_CHART = {
    TYPE_NORMAL: {TYPE_SPIRIT: 0, TYPE_EARTH: 0.5, TYPE_LIGHT: 0.5},
    TYPE_FIRE: {TYPE_FIRE: 0.5, TYPE_WATER: 0.5, TYPE_GRASS: 2, TYPE_ICE: 2, TYPE_EARTH: 0.5, TYPE_DRAGON: 0.5},
    TYPE_WATER: {TYPE_WATER: 0.5, TYPE_GRASS: 0.5, TYPE_FIRE: 2, TYPE_EARTH: 2, TYPE_DRAGON: 0.5},
    TYPE_GRASS: {TYPE_FIRE: 0.5, TYPE_WATER: 2, TYPE_GRASS: 0.5, TYPE_EARTH: 2, TYPE_WIND: 0.5},
    TYPE_ELECTRIC: {TYPE_WATER: 2, TYPE_ELECTRIC: 0.5, TYPE_GRASS: 0.5, TYPE_EARTH: 0, TYPE_WIND: 2, TYPE_DRAGON: 0.5},
    TYPE_ICE: {TYPE_GRASS: 2, TYPE_EARTH: 2, TYPE_WATER: 0.5, TYPE_FIRE: 0.5, TYPE_DRAGON: 2, TYPE_WIND: 2},
    TYPE_DARK: {TYPE_NORMAL: 2, TYPE_SPIRIT: 2, TYPE_DARK: 0.5, TYPE_LIGHT: 0.5},
    TYPE_SPIRIT: {TYPE_NORMAL: 0, TYPE_SPIRIT: 2, TYPE_DARK: 0.5},
    TYPE_DRAGON: {TYPE_DRAGON: 2, TYPE_LIGHT: 0.5},
    TYPE_EARTH: {TYPE_FIRE: 2, TYPE_WATER: 0.5, TYPE_GRASS: 0.5, TYPE_ELECTRIC: 2, TYPE_WIND: 0, TYPE_ICE: 2},
    TYPE_WIND: {TYPE_GRASS: 2, TYPE_ELECTRIC: 0.5, TYPE_EARTH: 2, TYPE_ICE: 0.5},
    TYPE_LIGHT: {TYPE_DARK: 2, TYPE_SPIRIT: 2, TYPE_NORMAL: 0.5, TYPE_DRAGON: 0.5},
}

# Growth rates: CUMULATIVE XP to reach level N
# Formula: cumulative_xp = level^2 * factor / 4
# FAST: early-route, evolve ~lvl 16-22 in 15-25 battles
# MEDIUM: starters, evolve ~lvl 16 in 15-25 battles
# SLOW: pseudo-legendaries, evolve ~lvl 35-42 in 60-100 battles
GROWTH_FAST = 4
GROWTH_MEDIUM = 8
GROWTH_SLOW = 10

def xp_for_level(level, growth_rate):
    if level <= 1:
        return 0
    return int((level ** 2) * growth_rate / 4)

# Stat calculation at level: base * level / 50 + 5 (rough Pokemon-style)
def calc_stat(base, level):
    return max(1, int(base * level / 50 + 5))

def calc_hp(base, level):
    return max(1, int((base * 2 * level / 100) + level + 10))

# Capture rates
CAPTURE_BASE = 45
SPHERE_NORMAL = 1.0
SPHERE_GREAT = 1.5
SPHERE_ULTRA = 2.0
SPHERE_MASTER = 255.0

# Items
ITEM_POTION = "Potion"
ITEM_SUPER_POTION = "Super Potion"
ITEM_HYPER_POTION = "Hyper Potion"
ITEM_FULL_HEAL = "Full Heal"
ITEM_SPHERE = "Soul Sphere"
ITEM_GREAT_SPHERE = "Great Sphere"
ITEM_ULTRA_SPHERE = "Ultra Sphere"
ITEM_MASTER_SPHERE = "Master Sphere"
ITEM_X_ATTACK = "X Attack"
ITEM_X_DEFENSE = "X Defense"
ITEM_REVIVE = "Revive"
ITEM_FULL_REVIVE = "Full Revive"
ITEM_ESCAPE_ROPE = "Escape Rope"
ITEM_BADGE_CASE = "Badge Case"
ITEM_TM_EMBER = "TM Ember"
ITEM_TM_WATER_GUN = "TM Water Gun"
ITEM_TM_VINE_WHIP = "TM Vine Whip"
ITEM_TM_THUNDERSHOCK = "TM Thundershock"
ITEM_TM_ICE_SHARD = "TM Ice Shard"
ITEM_TM_BITE = "TM Bite"
ITEM_TM_SHADOW_BALL = "TM Shadow Ball"
ITEM_TM_DRAGON_CLAW = "TM Dragon Claw"
ITEM_TM_STONE_EDGE = "TM Stone Edge"
ITEM_TM_AIR_SLASH = "TM Air Slash"
ITEM_TM_DAZZLING_GLEAM = "TM Dazzling Gleam"
ITEM_TM_FLAMETHROWER = "TM Flamethrower"
ITEM_TM_HYDRO_PUMP = "TM Hydro Pump"
ITEM_TM_SOLAR_BEAM = "TM Solar Beam"
ITEM_TM_THUNDERBOLT = "TM Thunderbolt"
ITEM_TM_BLIZZARD = "TM Blizzard"
ITEM_TM_EARTHQUAKE = "TM Earthquake"
ITEM_TM_CRUNCH = "TM Crunch"
ITEM_TM_RECOVER = "TM Recover"
ITEM_TM_SWORDS_DANCE = "TM Swords Dance"

# TM compatibility: TM item -> list of types that can learn it
TM_COMPAT = {
    ITEM_TM_EMBER: [TYPE_FIRE],
    ITEM_TM_WATER_GUN: [TYPE_WATER],
    ITEM_TM_VINE_WHIP: [TYPE_GRASS],
    ITEM_TM_THUNDERSHOCK: [TYPE_ELECTRIC],
    ITEM_TM_ICE_SHARD: [TYPE_ICE],
    ITEM_TM_BITE: [TYPE_DARK, TYPE_NORMAL],
    ITEM_TM_SHADOW_BALL: [TYPE_SPIRIT, TYPE_DARK],
    ITEM_TM_DRAGON_CLAW: [TYPE_DRAGON],
    ITEM_TM_STONE_EDGE: [TYPE_EARTH],
    ITEM_TM_AIR_SLASH: [TYPE_WIND],
    ITEM_TM_DAZZLING_GLEAM: [TYPE_LIGHT],
    ITEM_TM_FLAMETHROWER: [TYPE_FIRE],
    ITEM_TM_HYDRO_PUMP: [TYPE_WATER],
    ITEM_TM_SOLAR_BEAM: [TYPE_GRASS],
    ITEM_TM_THUNDERBOLT: [TYPE_ELECTRIC],
    ITEM_TM_BLIZZARD: [TYPE_ICE],
    ITEM_TM_EARTHQUAKE: [TYPE_EARTH],
    ITEM_TM_CRUNCH: [TYPE_DARK],
    ITEM_TM_RECOVER: [TYPE_NORMAL],
    ITEM_TM_SWORDS_DANCE: [TYPE_NORMAL],
}

# TM moves: TM item -> move_id
TM_MOVES = {
    ITEM_TM_EMBER: "ember",
    ITEM_TM_WATER_GUN: "water_gun",
    ITEM_TM_VINE_WHIP: "vine_whip",
    ITEM_TM_THUNDERSHOCK: "thundershock",
    ITEM_TM_ICE_SHARD: "ice_shard",
    ITEM_TM_BITE: "bite",
    ITEM_TM_SHADOW_BALL: "shadow_ball",
    ITEM_TM_DRAGON_CLAW: "dragon_claw",
    ITEM_TM_STONE_EDGE: "stone_edge",
    ITEM_TM_AIR_SLASH: "air_slash",
    ITEM_TM_DAZZLING_GLEAM: "dazzling_gleam",
    ITEM_TM_FLAMETHROWER: "flamethrower",
    ITEM_TM_HYDRO_PUMP: "hydro_pump",
    ITEM_TM_SOLAR_BEAM: "solar_beam",
    ITEM_TM_THUNDERBOLT: "thunderbolt",
    ITEM_TM_BLIZZARD: "blizzard",
    ITEM_TM_EARTHQUAKE: "earthquake",
    ITEM_TM_CRUNCH: "crunch",
    ITEM_TM_RECOVER: "recover",
    ITEM_TM_SWORDS_DANCE: "swords_dance",
}

ALL_TM_ITEMS = list(TM_MOVES.keys())

ITEM_PRICES = {
    ITEM_POTION: 300,
    ITEM_SUPER_POTION: 700,
    ITEM_HYPER_POTION: 1200,
    ITEM_FULL_HEAL: 600,
    ITEM_SPHERE: 200,
    ITEM_GREAT_SPHERE: 600,
    ITEM_ULTRA_SPHERE: 1200,
    ITEM_MASTER_SPHERE: 10000,
    ITEM_X_ATTACK: 500,
    ITEM_X_DEFENSE: 500,
    ITEM_REVIVE: 1500,
    ITEM_FULL_REVIVE: 3000,
    ITEM_ESCAPE_ROPE: 200,
    ITEM_TM_EMBER: 3000,
    ITEM_TM_WATER_GUN: 3000,
    ITEM_TM_VINE_WHIP: 3000,
    ITEM_TM_THUNDERSHOCK: 3000,
    ITEM_TM_ICE_SHARD: 3000,
    ITEM_TM_BITE: 3000,
    ITEM_TM_SHADOW_BALL: 5000,
    ITEM_TM_DRAGON_CLAW: 5000,
    ITEM_TM_STONE_EDGE: 4000,
    ITEM_TM_AIR_SLASH: 4000,
    ITEM_TM_DAZZLING_GLEAM: 4000,
    ITEM_TM_FLAMETHROWER: 5000,
    ITEM_TM_HYDRO_PUMP: 5000,
    ITEM_TM_SOLAR_BEAM: 5000,
    ITEM_TM_THUNDERBOLT: 5000,
    ITEM_TM_BLIZZARD: 5000,
    ITEM_TM_EARTHQUAKE: 5000,
    ITEM_TM_CRUNCH: 4000,
    ITEM_TM_RECOVER: 5000,
    ITEM_TM_SWORDS_DANCE: 4000,
}

# Trainer AI difficulties
AI_WILD = 0
AI_ROOKIE = 1
AI_TRAINER = 2
AI_GYM = 3
AI_ELITE = 4
AI_CHAMPION = 5

# Story flags
FLAG_STARTER_CHOSEN = "starter_chosen"
FLAG_RIVAL_MET = "rival_met"
FLAG_GYM_1 = "gym_1"
FLAG_GYM_2 = "gym_2"
FLAG_GYM_3 = "gym_3"
FLAG_GYM_4 = "gym_4"
FLAG_GYM_5 = "gym_5"
FLAG_GYM_6 = "gym_6"
FLAG_GYM_7 = "gym_7"
FLAG_GYM_8 = "gym_8"
FLAG_EVIL_1 = "evil_1"
FLAG_EVIL_2 = "evil_2"
FLAG_EVIL_3 = "evil_3"
FLAG_CHAMPION = "champion"
FLAG_GAME_COMPLETE = "game_complete"

# Colors for UI
COLOR_BG = (24, 24, 32)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GRAY = (128, 128, 128)
COLOR_LIGHT_GRAY = (200, 200, 200)
COLOR_RED = (220, 50, 50)
COLOR_GREEN = (50, 200, 50)
COLOR_BLUE = (50, 100, 220)
COLOR_YELLOW = (240, 220, 50)
COLOR_HP_GREEN = (80, 200, 80)
COLOR_HP_YELLOW = (240, 200, 50)
COLOR_HP_RED = (220, 60, 60)
COLOR_MENUBG = (40, 40, 56)
COLOR_SELECT = (80, 120, 200)
COLOR_BATTLE_BG = (48, 48, 64)

# Map tile types
TILE_GRASS = 0
TILE_TALL_GRASS = 1
TILE_PATH = 2
TILE_WATER = 3
TILE_TREE = 4
TILE_WALL = 5
TILE_DOOR = 6
TILE_NPC = 7
TILE_CHEST = 8
TILE_SIGN = 9
TILE_HEAL = 10
TILE_SHOP = 11
TILE_GYM = 12
TILE_GROUND = 13
TILE_ROOF = 14
TILE_BRIDGE = 15
TILE_ROCK = 16

TILE_COLORS = {
    TILE_GRASS: (100, 180, 80),
    TILE_TALL_GRASS: (70, 150, 50),
    TILE_PATH: (200, 180, 140),
    TILE_WATER: (64, 128, 220),
    TILE_TREE: (40, 100, 40),
    TILE_WALL: (140, 120, 100),
    TILE_DOOR: (160, 100, 50),
    TILE_GROUND: (180, 160, 120),
    TILE_HEAL: (220, 100, 100),
    TILE_SHOP: (100, 160, 220),
    TILE_SIGN: (160, 140, 100),
    TILE_GYM: (220, 180, 60),
    TILE_ROOF: (180, 60, 60),
    TILE_BRIDGE: (160, 120, 70),
    TILE_ROCK: (100, 90, 80),
}

WALKABLE_TILES = {TILE_GRASS, TILE_TALL_GRASS, TILE_PATH, TILE_GROUND, TILE_DOOR, TILE_HEAL, TILE_SHOP, TILE_GYM, TILE_BRIDGE, TILE_SIGN}
ENCOUNTER_TILES = {TILE_TALL_GRASS}

# Encounter rates per area
ENCOUNTER_RATERoute = 0.15
ENCOUNTER_RATECave = 0.10
ENCOUNTER_RATEWater = 0.10
